name: 🔄 Sync `copilot/.vscode` from `doggy8088/github-copilot-configs`

on:
  schedule:
    - cron: "30 1 * * *" # 每日 01:30 UTC（台灣時間 09:30）
  workflow_dispatch:

jobs:
  sync_vscode_config:
    runs-on: ubuntu-latest

    steps:
      - name: 🔧 Configure Git and check token
        env:
          GIT_TOKEN: ${{ secrets.SYNC_PAT }}
        run: |
          if [ -z "$GIT_TOKEN" ]; then
            echo "❌ SYNC_PAT is missing!"
            exit 1
          fi

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 🧾 Checkout your repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🌐 Clone `.vscode` folder from upstream
        run: |
          echo "📥 Cloning doggy8088/github-copilot-configs repo..."
          git clone --depth=1 https://github.com/doggy8088/github-copilot-configs.git temp-configs

          echo "UPSTREAM_COMMIT=$(cd temp-configs && git rev-parse --short HEAD)" >> $GITHUB_ENV

          mkdir -p copilot
          rm -rf copilot/.vscode
          cp -r temp-configs/.vscode copilot/ || echo "⚠️ No .vscode found"

          rm -rf temp-configs

      - name: 📦 Commit and push if changed
        env:
          GIT_TOKEN: ${{ secrets.SYNC_PAT }}
        run: |
          git add copilot/.vscode
          git diff --cached --quiet && echo "✅ No changes to commit." && exit 0

          git commit -m "🔄 Sync copilot/.vscode from doggy8088/github-copilot-configs (${UPSTREAM_COMMIT}) [bot][action]"
          git push https://x-access-token:${GIT_TOKEN}@github.com/XD3an/awesome-ai-coding.git HEAD:main
